### ISSUE TITLE
Portable plugins

### ISSUE THREAD

**Issue by SebastienTs** [imagingbook/imagej1-plugin-eclipse#1]

**Comment by imagingbook** [comment]
Hi, just wondered if you could resolve your problem.
Note that the setup in this repo is meant for very simple projects only. If you have non-plugin classes I recommend to create a common JAR file and place it in `<ImageJ>/jars/`, where ImageJ will find it. For portability I suggest to let Maven do the job, as shown in this repository: https://github.com/imagingbook/imagingbook-maven-demo-project

--Wilhelm

**Comment by SebastienTs** [comment]
Hey Wilhelm,

Thanks a lot for asking! Yes, I understood that the default my_plugins
folder in the src-plugins could actually be renamed to anything else, and
that IntelliJ does the job of creating a folder with the same name in
plugins and copy the class files compiled from all plugin files found at
this location. I guess that creating a java file for a plugin at the root
of src-plugins would work equally and that in this case the plugin would be
"portable" (no need to copy it to a subfolder with a specific name in the
target IJ install).

I am still curious about how this automation is configured in IntelliJ
(where should I look?). About extra classes called by a plugin, I take good
note. I am only getting started with Java (I program mostly in Python,
Matlab and C) so I still have to understand the way Maven works and when it
is absolutely necessary...

Thanks again for your help!
Best,
S.

**Comment by imagingbook** [comment]
OK, I think I know what you are after...
First note that `my_plugins` is not merely a folder but also the root of a Java "package", so you cannot simply rename the folder. But you can easily rename the package in your favorite IDE and that will rename the folder too. Alternatively, you can move (or copy) the contained source file(s) -- also within your IDE -- one level up to the `default package`. In this case, the compiled `.class` files should automatically appear at the top of ImageJ's `plugins` folder. I do not use IntelliJ regularly, but I know it is very user-friendly and intuitive.
There is no need for Maven at this level and I would not touch it unless you have solid experience with Java.
Hope this helps ...

**Comment by SebastienTs** [comment]
It surely does! Thanks a lot!
S.
